/*
 * Auction Bid Tracker
 *
 * This is an example server for auction bid tracker.
 *
 * API version: 1.0.0
 * Contact: antony.h@riseup.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request, 
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface { 
	AddItem(http.ResponseWriter, *http.Request)
	BidItemById(http.ResponseWriter, *http.Request)
	CloseItem(http.ResponseWriter, *http.Request)
	GetWinningBidByItemId(http.ResponseWriter, *http.Request)
	ListAllBidsByItemId(http.ResponseWriter, *http.Request)
	ListAllBidsByUserId(http.ResponseWriter, *http.Request)
	ListAllItems(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type DefaultApiServicer interface { 
	AddItem(Item) (interface{}, error)
	BidItemById(string, Bidding) (interface{}, error)
	CloseItem(string) (interface{}, error)
	GetWinningBidByItemId(string) (interface{}, error)
	ListAllBidsByItemId(string) (interface{}, error)
	ListAllBidsByUserId(string) (interface{}, error)
	ListAllItems() (interface{}, error)
}
