/*
 * Auction Bid Tracker
 *
 * This is an example server for auction bid tracker.
 *
 * API version: 1.0.0
 * Contact: antony.h@riseup.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{ service: s }
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{ 
		{
			"BidItemById",
			strings.ToUpper("Post"),
			"/v1/item/{id}",
			c.BidItemById,
		},
		{
			"GetWinningBidByItemId",
			strings.ToUpper("Get"),
			"/v1/item/{id}/winning",
			c.GetWinningBidByItemId,
		},
		{
			"ListAllBidsByItemId",
			strings.ToUpper("Get"),
			"/v1/item/{id}",
			c.ListAllBidsByItemId,
		},
		{
			"ListAllBidsByUserId",
			strings.ToUpper("Get"),
			"/v1/user/{id}",
			c.ListAllBidsByUserId,
		},
	}
}

// BidItemById - 
func (c *DefaultApiController) BidItemById(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id := params["id"]
	bidding := &Bidding{}
	if err := json.NewDecoder(r.Body).Decode(&bidding); err != nil {
		w.WriteHeader(500)
		return
	}
	
	result, err := c.service.BidItemById(id, *bidding)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// GetWinningBidByItemId - 
func (c *DefaultApiController) GetWinningBidByItemId(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id := params["id"]
	result, err := c.service.GetWinningBidByItemId(id)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// ListAllBidsByItemId - 
func (c *DefaultApiController) ListAllBidsByItemId(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id := params["id"]
	result, err := c.service.ListAllBidsByItemId(id)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// ListAllBidsByUserId - 
func (c *DefaultApiController) ListAllBidsByUserId(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	id := params["id"]
	result, err := c.service.ListAllBidsByUserId(id)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}
