/*
 * Auction Bid Tracker
 *
 * This is an example server for auction bid tracker.
 *
 * API version: 1.0.0
 * Contact: antony.h@riseup.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{service: s}
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{
		{
			"AddItem",
			strings.ToUpper("Post"),
			"/v1/item",
			c.AddItem,
		},
		{
			"BidItemById",
			strings.ToUpper("Post"),
			"/v1/bid/{item_name}",
			c.BidItemById,
		},
		{
			"CloseItem",
			strings.ToUpper("Put"),
			"/v1/item/{item_name}/close",
			c.CloseItem,
		},
		{
			"GetWinningBidByItemId",
			strings.ToUpper("Get"),
			"/v1/bid/{item_name}/winning",
			c.GetWinningBidByItemId,
		},
		{
			"ListAllBidsByItemId",
			strings.ToUpper("Get"),
			"/v1/bid/{item_name}",
			c.ListAllBidsByItemId,
		},
		{
			"ListAllBidsByUserId",
			strings.ToUpper("Get"),
			"/v1/user/{id}",
			c.ListAllBidsByUserId,
		},
		{
			"ListAllItems",
			strings.ToUpper("Get"),
			"/v1/items",
			c.ListAllItems,
		},
	}
}

// AddItem -
func (c *DefaultApiController) AddItem(w http.ResponseWriter, r *http.Request) {
	item := &Item{}
	if err := json.NewDecoder(r.Body).Decode(&item); err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.AddItem(*item)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, http.StatusCreated, w)
}

// BidItemById -
func (c *DefaultApiController) BidItemById(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	itemName := params["itemName"]
	bidding := &Bidding{}
	if err := json.NewDecoder(r.Body).Decode(&bidding); err != nil {
		w.WriteHeader(500)
		return
	}

	accepted, err := c.service.BidItemById(itemName, *bidding)
	if err != nil {
		switch err {
		case auction.ErrItemNotExist:
			w.WriteHeader(http.StatusNotFound)
		case auction.ErrAuctionClose:
			w.WriteHeader(http.StatusBadRequest)
		default:
			w.WriteHeader(500)
		}

		return
	}
	if accepted.(bool) {
		EncodeJSONResponse(nil, http.StatusCreated, w)
	} else {
		EncodeJSONResponse(nil, http.StatusBadRequest, w)
	}
}

// CloseItem -
func (c *DefaultApiController) CloseItem(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	itemName := params["itemName"]
	result, err := c.service.CloseItem(itemName)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, http.StatusAccepted, w)
}

// GetWinningBidByItemId -
func (c *DefaultApiController) GetWinningBidByItemId(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	itemName := params["itemName"]
	winning, err := c.service.GetWinningBidByItemId(itemName)
	if err != nil {
		switch err {
		case auction.ErrItemNotExist:
			w.WriteHeader(http.StatusNotFound)
		default:
			w.WriteHeader(500)
		}
		return
	}
	if winning != nil {
		EncodeJSONResponse(winning, nil, w)
	} else {
		EncodeJSONResponse(nil, http.StatusNoContent, w)
	}
}

// ListAllBidsByItemId -
func (c *DefaultApiController) ListAllBidsByItemId(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	itemName := params["itemName"]
	result, err := c.service.ListAllBidsByItemId(itemName)
	if err != nil {
		switch err {
		case auction.ErrItemNotExist:
			w.WriteHeader(http.StatusNotFound)
		default:
			w.WriteHeader(500)
		}
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// ListAllBidsByUserId -
func (c *DefaultApiController) ListAllBidsByUserId(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	id := params["id"]
	activities, err := c.service.ListAllBidsByUserId(id)
	if err != nil {
		switch err {
		case auction.ErrUserNotExist:
			w.WriteHeader(http.StatusNotFound)
		default:
			w.WriteHeader(500)
		}
		return
	}

	EncodeJSONResponse(activities, nil, w)
}

// ListAllItems -
func (c *DefaultApiController) ListAllItems(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.ListAllItems()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
