/*
 * Auction Bid Tracker
 *
 * This is an example server for auction bid tracker.
 *
 * API version: 1.0.0
 * Contact: antony.h@riseup.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Activity struct {

	Item Item `json:"item,omitempty"`

	Bid Bidding `json:"bid,omitempty"`
}
